name: Deploy to Production(DataPortal->Core)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Deploy to AWS EC2 Instance
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credenqtials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_EC2_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_EC2_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://dataportal-deploy-bucket/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name Dataportal --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name core --s3-location bucket=dataportal-deploy-bucket,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
